<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault></PropertyGroup><ItemGroup><ProjectReference Include="../PropTest.Infrastructure/PropTest.Infrastructure.csproj"/><PackageReference Include="Avalonia.Desktop" Version="11.2.5"/><PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5"/><PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5"/></ItemGroup></Project>
