#pragma once
const char boardPage[] PROGMEM = R"HTML(<!doctype html><html lang="uk"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PROpTEST · Плата v2</title><style>
*{box-sizing:border-box}body{margin:0;background:#eef2f6;color:#182b40;font:16px system-ui,sans-serif}main{max-width:800px;margin:32px auto;padding:0 18px}h1{margin-bottom:4px}h2{font-size:21px;margin-top:0}.muted{color:#596b7d;line-height:1.5}section{background:white;border-radius:14px;padding:24px;margin:18px 0;box-shadow:0 3px 14px #14283a09}label{display:block;margin:12px 0 6px}input,button{font:inherit;padding:12px;border:1px solid #b5c2cf;border-radius:8px;min-width:0}input[type=password],input[type=text]{width:100%}button{background:#e9eef3;color:inherit;cursor:pointer}button:disabled{opacity:.45;cursor:default}.primary{background:#176e64;color:white;border-color:#176e64}.stop{background:#b72521;color:white;border-color:#b72521;font-weight:700}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row input[type=number]{width:110px}#message{position:sticky;top:12px;z-index:2;white-space:pre-wrap;padding:14px;background:#e2eaf3;border-radius:8px;line-height:1.5}#reading{font-size:26px;font-weight:650;margin:16px 0}input[type=file]{width:100%}progress{width:100%;height:14px}small{line-height:1.5;display:block}a{color:#176e64}@media(max-width:450px){section{padding:18px}main{margin-top:20px}.row button{flex-grow:1}}
</style><main><h1>PROpTEST <span class="muted">v2</span></h1><p class="muted">S3-Connect 0.3.0 · Wi-Fi, оновлення та перевірка ESC</p>
<section id="login"><h2>З’єднання з платою</h2><p class="muted">Ноутбук залишається у вашій Wi-Fi мережі. Введіть пароль самої плати — його можна скопіювати у програмі через USB. Це не пароль роутера.</p><label for="key">Пароль плати</label><input id="key" type="password" autocomplete="off"><div class="row" style="margin-top:12px"><button id="eye" type="button">Показати пароль</button><button id="connect" class="primary">Підключитися</button></div></section>
<div id="message" role="status" aria-live="polite">Підключіться, щоб прочитати стан плати.</div>
<section><h2>Короткий тест · GPIO14</h2><p class="muted">Старий Hobbywing: білий провід → GPIO14, чорний → GND. Першу перевірку робіть зі знятим пропелером. Це перевірка керування, без вимірювання тяги та струму.</p><div id="reading">Стан виходу ще не прочитано</div><label for="gas">Газ, % · максимум 10</label><div class="row"><input id="gas" type="number" min="0" max="10" step="0.1" value="0" disabled><button id="apply" disabled>Задати газ</button></div><div class="row" style="margin-top:16px"><button id="arm" class="primary" disabled>Підготувати тест</button><button id="stop" class="stop" disabled>■ STOP</button></div><p class="muted">Підготовка залишає газ на нулі. Тест триває до 30 секунд. Без команд протягом 1 секунди плата зупиняє вихід; повторний запуск лише вручну.</p></section>
<section><h2>Оновлення через Wi-Fi</h2><p class="muted">Виберіть пакет PROpTEST <b>.ptfw</b>. Під час оновлення керування мотором заблоковане. Живлення плати має залишатися підключеним.</p><label for="file">Файл прошивки</label><input id="file" type="file" accept=".ptfw" disabled><button id="update" style="margin:12px 0" disabled>Завантажити оновлення</button><progress id="progress" max="100" value="0"></progress><small class="muted">Перевіряються тип пакета, розмір і SHA-256. Нова версія записується в окремий розділ. Після перезапуску ця сторінка перевірить зв’язок і підтвердить запуск; без підтвердження протягом 60 секунд плата повернеться до попередньої версії.</small></section>
<p class="muted">Працює лише в довіреній локальній мережі. Не відкривайте доступ до плати з інтернету.</p></main>
<script>
const $=id=>document.getElementById(id);let auth='',token='',busy=false,pumping=false,connected=false;
const reasons={STOP:'Зупинено',LINK_LOST:'Зупинено: втрачено зв’язок',TIME_LIMIT:'Зупинено: минуло 30 секунд',PWM_FAILED:'Помилка виходу GPIO14',BOOT:'Плата запускається'};
function message(t){$('message').textContent=t}
async function api(path,data){let c=new AbortController(),timer=setTimeout(()=>c.abort(),2500);try{let r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{Authorization:auth,'X-Proptest':'1',...(data===undefined?{}:{'Content-Type':'application/x-www-form-urlencoded'})},body:data===undefined?undefined:new URLSearchParams(data),signal:c.signal});if(!r.ok)throw Error(await r.text());return r.json()}finally{clearTimeout(timer)}}
function draw(s){$('reading').textContent=`Задано ${(s.target/10).toFixed(1)}% · вихід ${(s.applied/10).toFixed(1)}%`;$('arm').disabled=!connected||busy||s.armed||s.pending||!s.ready;$('gas').disabled=$('apply').disabled=!token||busy||!s.armed;$('stop').disabled=!connected;$('update').disabled=$('file').disabled=!connected||busy||s.armed||s.pending;if(!s.armed){token='';$('gas').value=0}return s}
$('eye').onclick=()=>{let show=$('key').type==='password';$('key').type=show?'text':'password';$('eye').textContent=show?'Приховати пароль':'Показати пароль'};
async function sync(){let s=await api('/status');if(s.pending){await api('/confirm',{});s=await api('/status')}draw(s);return s}
$('connect').onclick=async()=>{try{auth='Basic '+btoa('proptest:'+$('key').value);let s=await sync();connected=true;draw(s);$('key').value='';message('Підключено · '+s.version+' · '+reasons[s.reason])}catch(e){message('Не вдалося підключитися: '+e.message)}};
$('arm').onclick=async()=>{try{let s=await api('/arm',{});token=s.token;draw(s);message('Готово. Газ 0%. Введіть потрібне значення до 10% і натисніть «Задати газ».')}catch(e){message(e.message)}};
$('apply').onclick=async()=>{let n=Number($('gas').value);if(!Number.isFinite(n)||n<0||n>10){message('Введіть газ від 0 до 10%.');return}try{draw(await api('/gas',{token,value:Math.round(n*10)}))}catch(e){await stop();message(e.message)}};
async function stop(){token='';try{draw(await api('/stop',{}));message('Зупинено. Вихід 0%.')}catch(e){message('Немає підтвердження Stop. Плата має зупинити вихід за таймером втрати зв’язку. '+e.message)}}
$('stop').onclick=stop;
setInterval(async()=>{if(!connected||busy||pumping)return;pumping=true;try{let was=!!token;let s=token?await api('/lease',{token}):await api('/status');draw(s);if(was&&!s.armed)message(reasons[s.reason]||s.reason)}catch(e){token='';connected=false;draw({target:0,applied:0,armed:false});$('reading').textContent='Зв’язок втрачено · вихід не підтверджений';message('Зв’язок втрачено. Повторно натисніть «Підключитися». Автоматичного запуску немає.')}finally{pumping=false}},200);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&token)stop()});window.addEventListener('pagehide',()=>{token='';fetch('/stop',{method:'POST',headers:{Authorization:auth,'X-Proptest':'1'},keepalive:true}).catch(()=>{})});
$('update').onclick=async()=>{let file=$('file').files[0];if(!file){message('Виберіть файл .ptfw.');return}busy=true;draw({target:0,applied:0,armed:false});try{let previous=await api('/stop',{});message('Передавання прошивки…');await new Promise((resolve,reject)=>{let x=new XMLHttpRequest();x.open('POST','/update');x.setRequestHeader('Authorization',auth);x.setRequestHeader('X-Proptest','1');x.timeout=120000;x.upload.onprogress=e=>{if(e.lengthComputable)$('progress').value=e.loaded/e.total*100};x.onload=()=>x.status===200?resolve():reject(Error(x.responseText));x.onerror=()=>reject(Error('Зв’язок перервався'));x.ontimeout=()=>reject(Error('Час передавання минув'));let f=new FormData();f.append('firmware',file);x.send(f)});message('Файл перевірено. Плата перезапускається…');let success=false;for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,1500));try{let s=await sync();if(s.uptime<45000&&s.slot!==previous.slot){message('Оновлення завершено · '+s.version);success=true;break}}catch{}}if(!success)throw Error('Запуск не підтверджено. Перевірте з’єднання; без підтвердження працює повернення попередньої версії.')}catch(e){message('Оновлення: '+e.message)}finally{busy=false;try{draw(await api('/status'))}catch{connected=false}}};
</script></html>)HTML";
